"""Initial schema

Revision ID: bc5bdd02ba25
Revises: 
Create Date: 2026-07-06 14:43:11.166478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5bdd02ba25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FoodItems',
    sa.Column('FoodItemId', sa.Integer(), nullable=False),
    sa.Column('FoodItemName', sa.String(length=100), nullable=False),
    sa.Column('FoodPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('FoodItemId'),
    sa.UniqueConstraint('FoodItemName')
    )
    op.create_table('Orders',
    sa.Column('OrderId', sa.Integer(), nullable=False),
    sa.Column('OrderPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Status', sa.String(length=30), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('OrderId')
    )
    op.create_table('FoodItemOrder',
    sa.Column('FoodItemOrderId', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['FoodItems.FoodItemId'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.OrderId'], ),
    sa.PrimaryKeyConstraint('FoodItemOrderId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FoodItemOrder')
    op.drop_table('Orders')
    op.drop_table('FoodItems')
    # ### end Alembic commands ###
