from enum import Enum


class ErrorCode(str, Enum):
    EMPTY_CART = "EMPTY_CART"
    FOOD_NOT_FOUND = "FOOD_NOT_FOUND"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    ORDER_CREATION_FAILED = "ORDER_CREATION_FAILED"
    INVALID_LLM_RESPONSE = "INVALID_LLM_RESPONSE"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INTENT_NOT_FOUND = "INTENT_NOT_FOUND"